---
 - name: coping the file
   hosts: all
   become: true
   tasks:
      - name: coping the files
        ansible.builtin.copy:
          src: /index.html
          dest: /var/www/html/index.html
          owner: root
          mode: '0644'
      - name: starting the service
        ansible.builtin.service:
           name: apache2
           state: started
           enabled: true

...

