---
 - name: coping the file
   hosts: all
   become: true
   tasks:
      - name: coping the files
        ansible.builtin.copy:
          src: /ansible/index.html
          dest: /var/www/html/index.html
...