---
 - name: coping the file
   become: true
   tasks:
      - name: coping the files
        ansible.builtin.copy:
          src: /ansible/index.hmtl
          dest: /var/www/html
          owner: root
          mode: 0777
...