---
- name: creating the file
  hosts: all
  become: true
  tasks:
    - name: file creation
      ansible.builtin.file:
        path: /tmp/shiva.sh
        mode: 0777
        owner: root
        state: touch
...