 - name: mongodb
   hosts: mongodb
   become: yes
   tasks:
     - name: Copy mongodb repo
       ansible.builtin.copy:
         src: mongodb.repo
         dest: /etc/apt/sources.list.d/mongodb.repo
     - name: Update apt cache
       ansible.builtin.apt:
        update_cache: yes

     - name: Install MongoDB
       ansible.builtin.apt:
        name: mongodb-org
        state: present
        
     - name: start the servce
       ansible.builtin.service:
         name: mongod
         state: started
         enabled: yes
     - name: replace the file
       ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
     - name: restart the mongodb
       ansible.builtin.service:
        name: mongod
        state: restarted