 - name: mongodb
   hosts: mongodb
   become: yes
   tasks:
     - name: copy mongo repo
       ansible.builtin.copy:
         src: /mongo.repo
         dest: /etc/apt/sources.list.d/mongo.repo
         owner: root
         mode: '0644'
     - name: Import MongoDB GPG key
       apt_key:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        state: present

     - name: Add MongoDB repository
       apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse
        state: present

     - name: Update apt cache
       ansible.builtin.apt:
        update_cache: yes

     - name: Install MongoDB
       ansible.builtin.apt:
        name: mongodb-org-4.4
        state: present
     - name: start the servce
       ansible.builtin.service:
         name: mongod
         state: started
         enabled: yes
     - name: replace the file
       ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
     - name: restart the mongodb
       ansible.builtin.service:
        name: mongod
        state: restarted