- name: install and run ngnix
  hosts: all
  become: yes
  tasks:
   - name: install ngix
     ansible.builtin.package:
        name: nginx
        state: present
   - name: run nginx
     ansible.builtin.service:
        name: nginx
        state: started    