- name: install and run ngnix
  hosts: all
  become: yes
  tasks:
   - name: install ngnix
     ansible.builtin.package:
        name: ngnix
        state: present
   - name: run ngnix
     ansible.builtin.service:
        name: ngnix
        state: started    