- name: install and run ngnix
  hosts: all
  become: yes
  tasks:
   - name: install apache2
     ansible.builtin.package:
        name: apache2
        state: present
   - name: run apache
     ansible.builtin.service:
        name: httpd
        state: started  



        