- name: install and run ngnix
  hosts: all
  become: yes
  tasks:
   - name: install apache
     ansible.builtin.package:
        name: apahce
        state: present
   - name: run apache
     ansible.builtin.service:
        name: apache
        state: started    