---
- name: tags
  hosts: all
  become: true
  tasks:
    - name: install apache
      tags: 
         - install apache
      ansible.builtin.apt:
          name: apache2
          state: present
    - name: start the service
      tags:
          - start
      ansible.builtin.service:
          name: apache2
          state: started 
          enabled: true


# root@ip-172-31-43-244:~/ansible# ansible-playbook -i inventory tags.yaml --tags 'install apache'
# root@ip-172-31-43-244:~/ansible# ansible-playbook -i inventory tags.yaml --list-tags
# 
# root@ip-172-31-43-244:~/ansible# ansible-playbook -i inventory tags.yaml --skip-tags 'start'