---
- hosts: all
  become: true
  tasks: 
    - name: install httpd
      ansible.builtin.package:
        name: apache2
        state: latest
    - name: start the httpd
      ansible.builtin.service:
         service: apache2
         state: started
...